// v0.2 Phase 2 — Poseidon + SmtLib deployment helper.
//
// Zeto_AnonEncNullifierKyc links three external libraries (confirmed via the compiled
// artifact's linkReferences): PoseidonUnit2L, PoseidonUnit3L, and SmtLib.
//
// The PoseidonUnitNL libraries in @iden3/contracts are *stubs* (empty function bodies) —
// their on-chain implementation is the bytecode generated by circomlibjs
// `poseidonContract.createCode(n)`, whose `poseidon(uint256[n])` selector matches the stub.
// This is the canonical iden3/Zeto deployment pattern (see
// vendor/zeto/solidity/ignition/modules/lib/deps.ts).
//
// SmtLib uses a runtime IHasher (the contract calls `setHasher(new PoseidonHasher())`),
// so SmtLib itself has no static Poseidon link — it deploys standalone. The pool's own
// bytecode embeds PoseidonHasher (via `new`), which is why the pool links PoseidonUnit2L/3L.

import { ethers } from "hardhat";
/* eslint-disable @typescript-eslint/no-var-requires */
const { poseidonContract } = require("circomlibjs");
/* eslint-enable @typescript-eslint/no-var-requires */

export interface PoseidonLibraries {
  poseidon2: string; // PoseidonUnit2L
  poseidon3: string; // PoseidonUnit3L
  smtLib: string; // SmtLib
}

/** Deploy a circomlibjs-generated Poseidon contract for `n` inputs; return its address. */
async function deployPoseidon(
  n: number,
  signer: any,
  overrides: Record<string, unknown> = {},
): Promise<string> {
  const abi = poseidonContract.generateABI(n);
  const bytecode = poseidonContract.createCode(n);
  const factory = new ethers.ContractFactory(abi, bytecode, signer);
  const c = await factory.deploy(overrides);
  await c.waitForDeployment();
  return await c.getAddress();
}

/**
 * Deploy PoseidonUnit2L, PoseidonUnit3L, and SmtLib. Returns the addresses in the shape
 * needed for the `libraries` map passed to getContractFactory / deployProxy.
 *
 * @param signer the deployer signer
 * @param overrides optional tx overrides (e.g. { gasLimit } for Hedera)
 */
export async function deployPoseidonAndSmt(
  signer: any,
  overrides: Record<string, unknown> = {},
): Promise<PoseidonLibraries> {
  const poseidon2 = await deployPoseidon(2, signer, overrides);
  const poseidon3 = await deployPoseidon(3, signer, overrides);

  const SmtLib = await ethers.getContractFactory("SmtLib", signer);
  const smt = await SmtLib.deploy(overrides);
  await smt.waitForDeployment();

  return {
    poseidon2,
    poseidon3,
    smtLib: await smt.getAddress(),
  };
}

/** Map Poseidon/SmtLib addresses to the link names the KYC pool's bytecode expects. */
export function librariesMap(libs: PoseidonLibraries) {
  return {
    "@iden3/contracts/contracts/lib/Poseidon.sol:PoseidonUnit2L": libs.poseidon2,
    "@iden3/contracts/contracts/lib/Poseidon.sol:PoseidonUnit3L": libs.poseidon3,
    "@iden3/contracts/contracts/lib/SmtLib.sol:SmtLib": libs.smtLib,
  };
}

/** Poseidon-only link map (for consumers that use the Poseidon units but not SmtLib). */
export function poseidonOnlyMap(libs: PoseidonLibraries) {
  return {
    "@iden3/contracts/contracts/lib/Poseidon.sol:PoseidonUnit2L": libs.poseidon2,
    "@iden3/contracts/contracts/lib/Poseidon.sol:PoseidonUnit3L": libs.poseidon3,
  };
}
